// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-8lqREVQj-vMuEG12iH9cMdD3_RtrzkQ',
    appId: '1:750561383449:web:a9b87dc63bfa9c17fd0688',
    messagingSenderId: '750561383449',
    projectId: 'campuslink-9e132',
    authDomain: 'campuslink-9e132.firebaseapp.com',
    storageBucket: 'campuslink-9e132.firebasestorage.app',
    measurementId: 'G-YXJEX18JPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy9MtfCdmLh6vPTiqvwLt6wKdSHMa9m8o',
    appId: '1:750561383449:android:4473cd39c8b32136fd0688',
    messagingSenderId: '750561383449',
    projectId: 'campuslink-9e132',
    storageBucket: 'campuslink-9e132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgiqJW8vLPSY21Gyfvp5vYSaXW9Ll8z5g',
    appId: '1:750561383449:ios:b41f9b4b2e95b781fd0688',
    messagingSenderId: '750561383449',
    projectId: 'campuslink-9e132',
    storageBucket: 'campuslink-9e132.firebasestorage.app',
    iosBundleId: 'com.example.campuslink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgiqJW8vLPSY21Gyfvp5vYSaXW9Ll8z5g',
    appId: '1:750561383449:ios:b41f9b4b2e95b781fd0688',
    messagingSenderId: '750561383449',
    projectId: 'campuslink-9e132',
    storageBucket: 'campuslink-9e132.firebasestorage.app',
    iosBundleId: 'com.example.campuslink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-8lqREVQj-vMuEG12iH9cMdD3_RtrzkQ',
    appId: '1:750561383449:web:4c5835df5e1e0a52fd0688',
    messagingSenderId: '750561383449',
    projectId: 'campuslink-9e132',
    authDomain: 'campuslink-9e132.firebaseapp.com',
    storageBucket: 'campuslink-9e132.firebasestorage.app',
    measurementId: 'G-XZTSP1TD97',
  );
}
